#!/usr/bin/env bash

set -e

BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DOTBOT_DIR="meta/dotbot"

cd "${BASEDIR}"


if [[ "$OSTYPE" == "linux-gnu"* ]]; then
    CONFIG="meta/dotbot-configs/linux.conf.yaml"
elif [[ "$OSTYPE" == "darwin"* ]]; then
    CONFIG="meta/dotbot-configs/macos.conf.yaml"
else
    echo Unknown OS type: \'$OSTYPE\'
    exit -1
fi


git submodule update --init --recursive "$DOTBOT_DIR"

python3 "$BASEDIR/$DOTBOT_DIR/bin/dotbot" -d "$BASEDIR" -c "$CONFIG" "$@"
