syntax on

set noerrorbells
set tabstop=4 softtabstop=4
set shiftwidth=4
set expandtab
set smartindent
set number relativenumber
set nowrap
set smartcase

set noswapfile
set nobackup
set undodir=~/.vim/undodir
set undofile

set incsearch

set colorcolumn=80
highlight ColorColumn ctermbg=gray guibg=blue
set signcolumn=yes
set scrolloff=8
set cursorline
set termguicolors
set cmdheight=2


call plug#begin('~/.vim/plugged')
Plug 'gruvbox-community/gruvbox'
call plug#end()

colorscheme gruvbox
set background=dark

inoremap jj <Esc>
inoremap <C-c> <Esc>
let mapleader = " "


vnoremap J :m '>+1<cr>gv=gv
vnoremap K :m '<-2<CR>gv=gv
