k9s:
  # Toggles whether k9s should exit when CTRL-C is pressed. When set to true, you will need to exit k9s via the :quit command. Default is false.
  noExitOnCtrlC: true

  logger:
    # Defines the number of lines to return. Default 100
    tail: 1000
    # Defines the total number of log lines to allow in the view. Default 1000
    buffer: 5000
