k9s:
  cluster: api-tatung-ocp-poc:6443
  namespace:
    active: gateway-pj
    lockFavorites: false
    favorites:
    - gateway-pj
    - default
  view:
    active: dp
  featureGates:
    nodeShell: false
  portForwardAddress: localhost
